version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: pip install pytest
      - run:
          name: Ejecutar pruebas
          command: pytest

workflows:
  build_and_test:
    jobs:
      - build-and-test
